/** 
 * @mbggenerated
 * This file is automatically generated by MyBatis Generator, do not modify!
 * If this file generated again, it will be overwriting!
 */
package wang.xiaoluobo.web.entity;

import java.io.Serializable;

public class UsersEntity implements Serializable {
    /**
     * 主键, Table.Column is users.id
     */
    private Long id;

    /**
     * 名称, Table.Column is users.name
     */
    private String name;

    /**
     * 创建时间, Table.Column is users.create_time
     */
    private Long createTime;

    private static final long serialVersionUID = 1L;

    /**
     * 获取主键
     * @return java.lang.Long
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置主键
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取名称
     * @return java.lang.String
     */
    public String getName() {
        return name;
    }

    /**
     * 设置名称
     * @param name
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取创建时间
     * @return java.lang.Long
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * 设置创建时间
     * @param createTime
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * 
     * @param that
     * @return boolean
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UsersEntity other = (UsersEntity) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * 
     * @return int
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }
}