/**
 * @mbggenerated This file is automatically generated by MyBatis Generator, do not modify!
 * If this file generated again, it will be overwriting!
 */
package wang.xiaoluobo.web.mapper;

import org.apache.ibatis.annotations.Param;
import wang.xiaoluobo.web.entity.UsersEntity;
import wang.xiaoluobo.web.entity.UsersEntityExample;

import java.util.List;

public interface UsersEntityMapper {
    long countByExample(UsersEntityExample example);

    int deleteByExample(UsersEntityExample example);

    int insert(UsersEntity record);

    int insertSelective(UsersEntity record);

    List<UsersEntity> selectByExample(UsersEntityExample example);

    int updateByExampleSelective(@Param("record") UsersEntity record, @Param("example") UsersEntityExample example);

    int updateByExample(@Param("record") UsersEntity record, @Param("example") UsersEntityExample example);
}