server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  profiles:
    active: '@activatedProperties@'
